export const PROGRAMMING_LANGUAGES: string[] = [
    "JavaScript",
    "Python",
    "TypeScript",
    "Java",
    "C#",
    "C++",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "SQL",
    "HTML",
    "CSS",
    "Text",
];

export const LANGUAGE_EXTENSIONS: { [key: string]: string } = {
    'js': 'JavaScript',
    'jsx': 'JavaScript',
    'py': 'Python',
    'ts': 'TypeScript',
    'tsx': 'TypeScript',
    'java': 'Java',
    'cs': 'C#',
    'cpp': 'C++',
    'h': 'C++',
    'hpp': 'C++',
    'go': 'Go',
    'rs': 'Rust',
    'php': 'PHP',
    'rb': 'Ruby',
    'swift': 'Swift',
    'kt': 'Kotlin',
    'kts': 'Kotlin',
    'sql': 'SQL',
    'html': 'HTML',
    'css': 'CSS',
};